//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConecta.Repositories.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int Appointment_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Therapist_ID { get; set; }
        public System.DateTime Appointment_Date { get; set; }
        public System.TimeSpan Appointment_Time { get; set; }
        public int Appointment_State_ID { get; set; }
        public string Description { get; set; }
    
        public virtual Appointment_States Appointment_States { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Therapist Therapist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
    }
}
