//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConecta.Repositories.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Message_ID { get; set; }
        public int Sender_ID { get; set; }
        public int Recipient_ID { get; set; }
        public int Appointment_ID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Sent_DateTime { get; set; }
        public Nullable<bool> Is_Read { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
