//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConecta.Repositories.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Notification_ID { get; set; }
        public int User_ID { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Sent_DateTime { get; set; }
        public Nullable<bool> Is_Read { get; set; }
    
        public virtual User User { get; set; }
    }
}
