//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConecta.Repositories.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictogram
    {
        public int Pictogram_ID { get; set; }
        public int Category_ID { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public string TextDescription { get; set; }
    
        public virtual Pictogram_Categories Pictogram_Categories { get; set; }
    }
}
