//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConecta.Repositories.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int Progress_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Game_ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Score { get; set; }
        public string Observations { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
