//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConecta.Repositories.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Report_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Therapist_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string Progress_Summary { get; set; }
        public string FilePath { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Therapist Therapist { get; set; }
    }
}
