//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConecta.Repositories.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Notification_Settings
    {
        public int Setting_ID { get; set; }
        public int User_ID { get; set; }
        public bool Email_Notifications { get; set; }
        public bool Push_Notifications { get; set; }
        public bool Message_Notifications { get; set; }
        public bool Appointment_Reminders { get; set; }
    
        public virtual User User { get; set; }
    }
}
